### PR TITLE
build docker image from docker hub

### PR DESCRIPTION
**Pull request by jwgwalton**

### CODE REVIEW

**Review by benjefferies — CHANGES_REQUESTED** [review]
I get an error when trying to run this up with docker. I have got a docker postgres container running listening `-p 5431:5432`

```
could not connect to server: Cannot assign requested address
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5431?
```

**Comment by jwgwalton** [comment]
@benjefferies I've managed to get rid of my config changes when rebasing to try and squash it. I've updated them but they are based off the idea that its connecting to the docker network set up in ras-docker-dev. It would be possible to run that up and drop the existing Django server and run this branch up?

**Comment by benjefferies** [comment]
Good stuff. It might be worth adding a docker-compose.yml to make it easy to start the service in isolation and just a one liner in the README.md. Other than that looks good 👍

**Review by LJBabbage — APPROVED** [review]

**Review by benjefferies — APPROVED** [review]
Looks good. We should address the failure of the oauth app so that it waits for postgres if it's not there

**Pull request merged**
