### PR TITLE
Change to readme to try to force CI pipeline to fix itself

### PR DESCRIPTION
**Pull request by NickGrantX**
# Motivation and Context
The Concourse CI job `django-oauth2-test-ci-deploy` has been failing for 4 days with `no versions of image available` in the `git-info` step. Am trying to see if merging a new commit onto the master branch will trigger our Concourse woes to be cured.

# What has changed
Added a newline to the end of the README.md file.

# How to test?
Merge the PR. See what Concourse does.

# Links
Trello: https://trello.com/c/zX27SDMV

### CODE REVIEW

**Review by ryangrundy7 — COMMENTED** [review]
I think we might have to change the pipeline instead, looks like it can't pull down an image that it used to use.

**Comment by NickGrantX** [comment]
won't poking it all with a change cause a new image to be created?

**Review by ryangrundy7 — COMMENTED** [review]
@NickGrantONS Just looked on ras-deploy, it's trying to pull an image called `paasmule/curl-ssl-git`. On [docker-hub](https://hub.docker.com/r/paasmule/curl-ssl-git/), I can't see any tag which it can grab. Hasn't been updated in a while

**Comment by NickGrantX** [comment]
what in the heck is that?!?

**Comment by NickGrantX** [comment]
This ain't gonna fix it

**Pull request closed without merging**
